"""Build partition-targeted, non-promoting adjudication evidence."""
from pathlib import Path
import json,hashlib
from tools.fastloop_research.contract import canonical_json
ROOT=Path(__file__).resolve().parents[2]; SRC=ROOT/'data/goal_loop_v2/references/1308/reference-coordinate-authorized-v21.json'; PART=ROOT/'reports/semantic_public_partition_20260902/semantic-public-partition.json'; MATRIX=ROOT/'reports/candidate_opening_cut_impact_20260902/candidate-opening-cut-impact.json'; PAIR=ROOT/'reports/partition_resolved_cut_pair_20260902/partition-resolved-cut-pair.json'; OUT=ROOT/'reports/partition_targeted_adjudication_20260902'; IDS=('OP002','OP006','OP007','OP010')
def hs(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def h(v):return hashlib.sha256(canonical_json(v)).hexdigest()
def main():
 d=json.loads(SRC.read_text());p=json.loads(PART.read_text());m=json.loads(MATRIX.read_text());q=json.loads(PAIR.read_text()); by={x['opening_id']:x for x in q['openings']}; rows=[]
 for oid in IDS:
  x=by[oid]; imp=next(y for y in m['openings'] if y['opening_id']==oid); cell=next(y for y in p['cells'] if y['space_id']==x['public_cell_id']); rows.append({'opening_id':oid,'host_atom_id':x['host_atom_id'],'registered_segment_m':imp['segment_m'],'directed_side_assignment':x['directed_side_assignment'],'public_cell':{'space_id':cell['space_id'],'polygon_hash':cell['polygon_hash'],'polygons':cell['polygons']},'non_public_anchor_ids':x['non_public_anchor_ids'],'pre_cut_anchor_groups':imp['pre_cut_anchor_groups'],'post_cut_anchor_groups':imp['post_cut_anchor_groups'],'jamb_classification':'sufficient' if oid in ('OP002','OP010') else 'insufficient','jamb_threshold_m':.12,'sensitivity_stable':x['sensitivity_stable'],'cut_confirmation':False,'pair_confirmation':False,'adjacency_confirmation':False,'semantic_promotion':False,'build_authorized':False,'artifact_bindings':[]})
 out={'schema':'partition-targeted-adjudication-evidence-v1','source_structure_hash':d['structure_hash'],'source_document_sha256':hs(SRC),'target_aware_wall_candidate_hash':m['target_aware_wall_candidate_hash'],'cut_matrix_candidate_hash':m['candidate_hash'],'partition_file_sha256':hs(PART),'partition_candidate_hash':p['candidate_hash'],'pair_candidate_hash':q['candidate_hash'],'opening_ids':list(IDS),'openings':rows,'pair_confirmation':False,'adjacency_confirmation':False,'semantic_promotion':False,'score_effect':'none','build_authorized':False,'ready':False};out['candidate_hash']=h(out);OUT.mkdir(parents=True,exist_ok=True);(OUT/'partition-targeted-adjudication.json').write_text(json.dumps(out,indent=2)+'\n');(OUT/'REPORT.md').write_text('# Partition-targeted adjudication evidence\n\nOP002, OP006, OP007 and OP010 bind the repaired public cell geometry and distinct non-public baseline anchors. Jamb classification is sufficient for OP002/OP010 and insufficient for OP006/OP007 under the 0.12 m threshold. Candidate-only; no confirmation or promotion.\n');print(out['candidate_hash'])
if __name__=='__main__':main()
